Text concat setting
kintone-samples/plugin-samples pull request #202
Opened 2022-09-09 07:35 UTC by juridon

updated to es6
changed the data type of 'config'

2022-09-15 03:02 UTC, MaedaAs requested changes
プラグインのバージョンとインデントの修正をお願いします！

2022-09-15 05:13 UTC, juridon commented on examples/textConnect/config_js/config.js
> + jQuery.noConflict();
6dfe57bc60a2952ca25c2281bcaccf0d3c65bd13

インデントのズレ修正しました！

2022-09-16 00:31 UTC, juridon commented on examples/textConnect/config_js/config.js
> + jQuery.noConflict();
fdbb0c181bc7e7b65d127a74607e9376e061c721

desktop.js
mobile.js

についてもインデント修正しました！

2022-09-16 01:23 UTC, juridon commented on examples/textConnect/manifest.json
> +    "version": 1,
a5ffc3d7e674741c4ecdf0693f2bc2a1b7e04a2b

バージョン修正しました！

2022-09-16 04:32 UTC, merged